version: "2"
run:
  tests: true
linters:
  default: none
  enable:
    - gosec
    - govet
    - misspell
    - revive
    - staticcheck
    - unused
  settings:
    revive:
      confidence: 0.8
      severity: warning
      rules:
        - name: unreachable-code
        - name: errorf
        - name: range
        - name: superfluous-else
        - name: var-declaration
        - name: duplicated-imports
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      # Golangci-lint is no honoring the "lint:ignore" comments for staticcheck.
      - linters: [ staticcheck ]
        text: 'SA1019:'
      # Exclude ST1005 when it encounters errors starting with proper noun.
      - linters: [ staticcheck ]
        text: 'ST1005:'
        path: pkg/handlers/antreasvc/client.go
        source: return nil, fmt.Errorf\("Antrea
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gofmt
    - goimports
  settings:
    goimports:
      local-prefixes:
        - antrea.io/antrea-ui
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
