# golangci-lint configuration used for CI
run:
  tests: true
  timeout: 10m

linters-settings:
  goimports:
    local-prefixes: antrea.io/antrea-ui
  revive:
    ignore-generated-header: false
    severity: warning
    confidence: 0.8
    rules:
      - name: unreachable-code
      - name: errorf
      - name: range
      - name: superfluous-else
      - name: var-declaration
      - name: duplicated-imports

linters:
  disable-all: true
  enable:
    - misspell
    - gofmt
    - unused
    - staticcheck
    - gosec
    - goimports
    - govet
    - revive

issues:
  exclude-rules:
    # This is temporary
    # Golangci-lint is no honoring the "lint:ignore" comments for staticcheck
    - linters:
        - staticcheck
      text: "SA1019:"
