// Copyright 2024 Antrea Authors
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//

// Code generated by MockGen. DO NOT EDIT.
// Source: interface.go

// Package testing is a generated GoMock package.
package testing

import (
	context "context"
	reflect "reflect"

	v1 "antrea.io/antrea-ui/apis/v1"
	gomock "github.com/golang/mock/gomock"
)

// MockFlowStreamSubscriber is a mock of FlowStreamSubscriber interface.
type MockFlowStreamSubscriber struct {
	ctrl     *gomock.Controller
	recorder *MockFlowStreamSubscriberMockRecorder
}

// MockFlowStreamSubscriberMockRecorder is the mock recorder for MockFlowStreamSubscriber.
type MockFlowStreamSubscriberMockRecorder struct {
	mock *MockFlowStreamSubscriber
}

// NewMockFlowStreamSubscriber creates a new mock instance.
func NewMockFlowStreamSubscriber(ctrl *gomock.Controller) *MockFlowStreamSubscriber {
	mock := &MockFlowStreamSubscriber{ctrl: ctrl}
	mock.recorder = &MockFlowStreamSubscriberMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockFlowStreamSubscriber) EXPECT() *MockFlowStreamSubscriberMockRecorder {
	return m.recorder
}

// Subscribe mocks base method.
func (m *MockFlowStreamSubscriber) Subscribe(ctx context.Context, filter *v1.FlowStreamFilter) (<-chan v1.FlowStreamEvent, <-chan error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Subscribe", ctx, filter)
	ret0, _ := ret[0].(<-chan v1.FlowStreamEvent)
	ret1, _ := ret[1].(<-chan error)
	return ret0, ret1
}

// Subscribe indicates an expected call of Subscribe.
func (mr *MockFlowStreamSubscriberMockRecorder) Subscribe(ctx, filter interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Subscribe", reflect.TypeOf((*MockFlowStreamSubscriber)(nil).Subscribe), ctx, filter)
}
