// Copyright 2024 Antrea Authors
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//

// Code generated by MockGen. DO NOT EDIT.
// Source: interface.go

// Package testing is a generated GoMock package.
package testing

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockResolver is a mock of Resolver interface.
type MockResolver struct {
	ctrl     *gomock.Controller
	recorder *MockResolverMockRecorder
}

// MockResolverMockRecorder is the mock recorder for MockResolver.
type MockResolverMockRecorder struct {
	mock *MockResolver
}

// NewMockResolver creates a new mock instance.
func NewMockResolver(ctrl *gomock.Controller) *MockResolver {
	mock := &MockResolver{ctrl: ctrl}
	mock.recorder = &MockResolverMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockResolver) EXPECT() *MockResolverMockRecorder {
	return m.recorder
}

// ClusterScopeProbeUsable mocks base method.
func (m *MockResolver) ClusterScopeProbeUsable() bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ClusterScopeProbeUsable")
	ret0, _ := ret[0].(bool)
	return ret0
}

// ClusterScopeProbeUsable indicates an expected call of ClusterScopeProbeUsable.
func (mr *MockResolverMockRecorder) ClusterScopeProbeUsable() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ClusterScopeProbeUsable", reflect.TypeOf((*MockResolver)(nil).ClusterScopeProbeUsable))
}

// NamespacesFor mocks base method.
func (m *MockResolver) NamespacesFor(username string, groups []string) ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NamespacesFor", username, groups)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// NamespacesFor indicates an expected call of NamespacesFor.
func (mr *MockResolverMockRecorder) NamespacesFor(username, groups interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NamespacesFor", reflect.TypeOf((*MockResolver)(nil).NamespacesFor), username, groups)
}
