// Copyright 2024 Antrea Authors
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//

// Code generated by MockGen. DO NOT EDIT.
// Source: interface.go

// Package testing is a generated GoMock package.
package testing

import (
	context "context"
	reflect "reflect"
	time "time"

	v1 "antrea.io/antrea-ui/apis/v1"
	metricstap "antrea.io/antrea-ui/pkg/handlers/metricstap"
	gomock "github.com/golang/mock/gomock"
)

// MockManager is a mock of Manager interface.
type MockManager struct {
	ctrl     *gomock.Controller
	recorder *MockManagerMockRecorder
}

// MockManagerMockRecorder is the mock recorder for MockManager.
type MockManagerMockRecorder struct {
	mock *MockManager
}

// NewMockManager creates a new mock instance.
func NewMockManager(ctrl *gomock.Controller) *MockManager {
	mock := &MockManager{ctrl: ctrl}
	mock.recorder = &MockManagerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockManager) EXPECT() *MockManagerMockRecorder {
	return m.recorder
}

// Families mocks base method.
func (m *MockManager) Families(ctx context.Context, id string) (*v1.MetricFamilyList, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Families", ctx, id)
	ret0, _ := ret[0].(*v1.MetricFamilyList)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Families indicates an expected call of Families.
func (mr *MockManagerMockRecorder) Families(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Families", reflect.TypeOf((*MockManager)(nil).Families), ctx, id)
}

// HasTap mocks base method.
func (m *MockManager) HasTap(id, owner string) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HasTap", id, owner)
	ret0, _ := ret[0].(bool)
	return ret0
}

// HasTap indicates an expected call of HasTap.
func (mr *MockManagerMockRecorder) HasTap(id, owner interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HasTap", reflect.TypeOf((*MockManager)(nil).HasTap), id, owner)
}

// Open mocks base method.
func (m *MockManager) Open(ctx context.Context, options metricstap.TapOptions) (string, <-chan metricstap.Event, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Open", ctx, options)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(<-chan metricstap.Event)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// Open indicates an expected call of Open.
func (mr *MockManagerMockRecorder) Open(ctx, options interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Open", reflect.TypeOf((*MockManager)(nil).Open), ctx, options)
}

// ParseInterval mocks base method.
func (m *MockManager) ParseInterval(interval string) (time.Duration, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ParseInterval", interval)
	ret0, _ := ret[0].(time.Duration)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ParseInterval indicates an expected call of ParseInterval.
func (mr *MockManagerMockRecorder) ParseInterval(interval interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ParseInterval", reflect.TypeOf((*MockManager)(nil).ParseInterval), interval)
}

// ResolveTarget mocks base method.
func (m *MockManager) ResolveTarget(id string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ResolveTarget", id)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ResolveTarget indicates an expected call of ResolveTarget.
func (mr *MockManagerMockRecorder) ResolveTarget(id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ResolveTarget", reflect.TypeOf((*MockManager)(nil).ResolveTarget), id)
}

// TargetGroups mocks base method.
func (m *MockManager) TargetGroups() []metricstap.TargetGroupStatus {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "TargetGroups")
	ret0, _ := ret[0].([]metricstap.TargetGroupStatus)
	return ret0
}

// TargetGroups indicates an expected call of TargetGroups.
func (mr *MockManagerMockRecorder) TargetGroups() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TargetGroups", reflect.TypeOf((*MockManager)(nil).TargetGroups))
}

// Targets mocks base method.
func (m *MockManager) Targets(ctx context.Context, targetGroup string) ([]v1.MetricsTarget, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Targets", ctx, targetGroup)
	ret0, _ := ret[0].([]v1.MetricsTarget)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Targets indicates an expected call of Targets.
func (mr *MockManagerMockRecorder) Targets(ctx, targetGroup interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Targets", reflect.TypeOf((*MockManager)(nil).Targets), ctx, targetGroup)
}

// UpdateSelections mocks base method.
func (m *MockManager) UpdateSelections(id, owner string, selections []v1.MetricsSelection) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateSelections", id, owner, selections)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateSelections indicates an expected call of UpdateSelections.
func (mr *MockManagerMockRecorder) UpdateSelections(id, owner, selections interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateSelections", reflect.TypeOf((*MockManager)(nil).UpdateSelections), id, owner, selections)
}

// ValidateSelections mocks base method.
func (m *MockManager) ValidateSelections(selections []v1.MetricsSelection) ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ValidateSelections", selections)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ValidateSelections indicates an expected call of ValidateSelections.
func (mr *MockManagerMockRecorder) ValidateSelections(selections interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ValidateSelections", reflect.TypeOf((*MockManager)(nil).ValidateSelections), selections)
}
