name: Build and push container images
on:
  pull_request:
    branches:
    - main
  push:
    branches:
    - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Check-out code
      uses: actions/checkout@v3
    - name: Build container images
      run: make
    - name: Push container images if needed
      if: ${{ github.repository == 'antrea-io/antrea-ui' && github.event_name == 'push' && github.ref == 'refs/heads/main' }}
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      run: |
        docker push antrea/antrea-ui-frontend
        docker push antrea/antrea-ui-backend
