name: Go
on:
  pull_request:
    branches:
    - main
    - release-*
  push:
    branches:
    - main
    - release-*

jobs:
  build:
    name: Build Go binaries
    runs-on: ubuntu-latest
    steps:
    - name: Check-out code
      uses: actions/checkout@v3
    - name: Set up Go using version from go.mod
      uses: actions/setup-go@v4
      with:
        go-version-file: 'go.mod'
    - name: Build binaries
      run: |
        make bin

  test:
    name: Run Go unit tests
    runs-on: ubuntu-latest
    steps:
    - name: Check-out code
      uses: actions/checkout@v3
    - name: Set up Go using version from go.mod
      uses: actions/setup-go@v4
      with:
        go-version-file: 'go.mod'
    - name: Run unit tests
      run: |
        make test

  tidy:
    name: Check tidiness
    runs-on: ubuntu-latest
    steps:
    - name: Check-out code
      uses: actions/checkout@v3
    - name: Set up Go using version from go.mod
      uses: actions/setup-go@v4
      with:
        go-version-file: 'go.mod'
    - name: Check tidiness
      run: |
        go mod tidy
        test -z "$(git status --porcelain)" || (echo "you should run 'go mod tidy' and commit the changes"; exit 1)
        make generate
        test -z "$(git status --porcelain)" || (echo "you should run 'make generate' and commit the changes"; exit 1)
    - name: Check copyright headers
      run: |
        make check-copyright

  golangci:
    name: Run golangci-lint
    runs-on: ubuntu-latest
    steps:
    - name: Check-out code
      uses: actions/checkout@v3
    - name: Run code linters
      run: |
        make golangci
