name: Go
on:
  pull_request:
    branches:
    - main
  push:
    branches:
    - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Check-out code
      uses: actions/checkout@v3
    - name: Set up Go using version from go.mod
      uses: actions/setup-go@v3
      with:
        go-version-file: 'go.mod'
    - name: Run unit tests
      run: |
        make test

  tidy:
    runs-on: ubuntu-latest
    steps:
    - name: Check-out code
      uses: actions/checkout@v3
    - name: Set up Go using version from go.mod
      uses: actions/setup-go@v3
      with:
        go-version-file: 'go.mod'
    - name: Check tidiness
      run: |
        go mod tidy
        test -z "$(git status --porcelain)" || (echo "you should run 'go mod tidy' and commit the changes"; exit 1)
        make generate
        test -z "$(git status --porcelain)" || (echo "you should run 'make generate' and commit the changes"; exit 1)

  golangci:
    runs-on: ubuntu-latest
    steps:
    - name: Check-out code
      uses: actions/checkout@v3
    - name: Run code linters
      run: |
        make golangci
