name: Node
on:
  pull_request:
    branches:
    - main
    - release-*
  push:
    branches:
    - main
    - release-*

jobs:
  yarn:
    name: Run Node checks
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: client/web/
    steps:
    - name: Check-out code
      uses: actions/checkout@v7
    - name: Set up Node
      uses: actions/setup-node@v7
      with:
        node-version: 24
    - name: Enable Corepack
      run: corepack enable
    - run: yarn install --immutable
    - run: yarn workspace @antrea/ui-components run build
    - run: yarn workspace antrea-ui run lint
    - run: yarn workspace antrea-ui run test

  ui-components:
    name: Run antrea-ui-components checks
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: client/web/
    steps:
    - name: Check-out code
      uses: actions/checkout@v7
    - name: Set up Node
      uses: actions/setup-node@v7
      with:
        node-version: 24
    - name: Enable Corepack
      run: corepack enable
    - run: yarn install --immutable
    - run: yarn workspace @antrea/ui-components run lint
    - run: yarn workspace @antrea/ui-components run test
