name: Process new release

on:
  release:
    types: [published]

jobs:
  upload-release-assets:
    name: Upload release assets
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Go using version from go.mod
      uses: actions/setup-go@v5
      with:
        go-version-file: 'go.mod'
    - name: Build assets
      env:
        TAG: ${{ github.ref }}
        PRERELEASE: ${{ github.event.release.prerelease }}
      run: |
        mkdir assets
        VERSION="${TAG:10}" ./hack/release/prepare-assets.sh ./assets
    - name: Upload all assets
      uses: alexellis/upload-assets@0.4.1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        asset_paths: '["./assets/*"]'

  update-website:
    name: Trigger website update for release
    needs: upload-release-assets
    runs-on: ubuntu-latest
    steps:
    - id: get-version
      env:
        TAG: ${{ github.ref }}
      run: |
        version=${TAG:10}
        echo "version=$version" >> $GITHUB_OUTPUT
    - name: Update Helm index with Antrea UI archive
      uses: benc-uk/workflow-dispatch@v1
      with:
        repo: antrea-io/website
        ref: refs/heads/main
        workflow: Update Helm index
        token: ${{ secrets.ANTREA_WEBSITE_WORKFLOW_DISPATCH_PAT }}
        inputs: ${{ format('{{ "archive-url":"https://github.com/antrea-io/antrea-ui/releases/download/{0}/antrea-ui-chart.tgz" }}', steps.get-version.outputs.version) }}
